package com.cpr.api.bean;

public class Record {
	
	/**
	 * The PRIMARY KEY from our Record table.
	 */
	private long id;
	
	/**
	 * The Right data from record for future comparison.
	 */
	private String dataRight;
	
	/**
	 * The Left data from record for future comparison.
	 */
	private String dataLeft;
	
	/**
	 * The constructor for this class
	 */
	public Record(Long id, String dataRight, String dataLeft) {
		this.id = id;
		this.dataRight = dataRight;
		this.dataLeft = dataLeft;
	}
	
	/**
	 * The default constructor for this class
	 */
	public Record() {}
    
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDataRight() {
		return dataRight;
	}

	public void setDataRight(String dataRight) {
		this.dataRight = dataRight;
	}

	public String getDataLeft() {
		return dataLeft;
	}

	public void setDataLeft(String dataLeft) {
		this.dataLeft = dataLeft;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dataLeft == null) ? 0 : dataLeft.hashCode());
		result = prime * result + ((dataRight == null) ? 0 : dataRight.hashCode());
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	
	/**
	 * The equals for this class, generated by Eclipse
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Record other = (Record) obj;
		if (dataLeft == null) {
			if (other.dataLeft != null)
				return false;
		} else if (!dataLeft.equals(other.dataLeft))
			return false;
		if (dataRight == null) {
			if (other.dataRight != null)
				return false;
		} else if (!dataRight.equals(other.dataRight))
			return false;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Record [id=" + id + ", dataRight=" + dataRight + ", dataLeft=" + dataLeft + "]";
	}
}
